version: 0.2

phases:
  pre_build:
    commands:
      - echo "Secondary source contents:"
      - ls -al $CODEBUILD_SRC_DIR_config
      - cp $CODEBUILD_SRC_DIR_config/application.yml ./src/main/resources/
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew build -x test
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ./LV3_final.jar
      - echo "✅ Copied JAR to ./LV3_final.jar"
      - ls -la ./ | grep LV3_final.jar

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - LV3_final.jar
    - scripts/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
