version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew build -x test
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ./LV3_final.jar
      - echo "✅ Copied JAR to ./LV3_final.jar"
      - ls -la ./ | grep LV3_final.jar

      # 스크립트 복사
      - cp -r ./scripts ./scripts_copy/
      - chmod +x ./scripts_copy/*.sh
      - echo "✅ Copied scripts to ./scripts_copy/"
      - ls -la ./scripts_copy/

      # appspec 복사
      - cp appspec.yml ./appspec.yml
      - echo "✅ Copied appspec.yml to ./"
      - ls -la ./ | grep appspec.yml

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - LV3_final.jar
    - scripts_copy/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
